//#define MODEL_NAME DARKNET_YOLOV3_TINY
//#define MODEL_NAME DARKNET_YOLOV3
//#define MODEL_NAME YOLOV2_CPU
//#define MODEL_NAME YOLOV2_NPU
#define MODEL_PART1_NAME RESNET18_NPU1
#define MODEL_PART2_NAME RESNET18_NPU2
#define MODEL_PART_DYNAMIC_NAME RESNET18_NPU_DYNAMIC
